### PR TITLE
Fix tag in digital ocean spaces

### PR DESCRIPTION
**Pull request by KAIOAVILA**
Fixes https://github.com/parse-community/parse-server-s3-adapter/issues/137

### CODE REVIEW

**Comment by KAIOAVILA** [comment]
Fix for issue https://github.com/parse-community/parse-server-s3-adapter/issues/137

**Comment by mtrezza** [comment]
I'm not sure we need an additional `isTagging` parameter for this. But before going into detail, let's first resolve the open questions in the issue.

**Comment by KAIOAVILA** [comment]
True, I will only try to make a treatment if it is empty the tags do not send to digital ocean spaces, what do you think?

**Comment by KAIOAVILA** [comment]
The problem is that digital ocean spaces don't accept tags anymore, so if they put tags in the files, it will give an error in the same way

**Comment by mtrezza** [comment]
Please see the discussion in #135.

The idea is that if tag is:
- `undefined` --> send no tag parameter to S3 endpoint
- `{}` --> send empty object to S3 endpoint

We want to stay true to the value the developer sets in the file upload. Do you see a change necessary in S3 adapter, in Parse Server or both for this?

**Comment by KAIOAVILA** [comment]
In this case I believe that the best would be only on the s3 adapter

Because in the documentation of digital ocean spaces, there is no longer to send tags, so even if I send an empty object, it will give an error

https://developers.digitalocean.com/documentation/spaces/#object

**Comment by KAIOAVILA** [comment]
I will close this PR, because as there is already another open resolving this, in the meantime I will be using my fork to solve my problem

**Comment by mtrezza** [comment]
> In this case I believe that the best would be only on the s3 adapter
Because in the documentation of digital ocean spaces, there is no longer to send tags, so even if I send an empty object, it will give an error

Yes, what I meant was that we want to give developers both options:
- Save a file with no tags (`undefined`) --> the S3 adapter should not send any tag property, not even an empty object
- Save a file with empty tag object (`{}`) --> the S3 adapter should send an empty tag object

**Pull request closed without merging**
